/**
 * Sync Routes
 * Handles player database sync and content creator discovery
 */

import express from 'express';
import db from '../db.js';
import { authenticate, requireAdmin } from '../middleware/auth.js';

const router = express.Router();

// POST /api/sync/players - Sync players from eFootballDB (admin only)
router.post('/players', authenticate, requireAdmin, async (req, res) => {
    try {
        const { players } = req.body;

        if (!players || !Array.isArray(players) || players.length === 0) {
            return res.status(400).json({ error: 'Players array required' });
        }

        // Add each player to database (upsert by name)
        const result = await db.savePlayers(players);

        // Add notification
        await db.saveNotification({
            type: 'system',
            message: `Player Registry Synced: ${players.length} players`,
            details: `Database updated with latest eFootballDB data`,
            timestamp: new Date().toLocaleTimeString()
        });

        res.json({
            success: true,
            count: result.count
        });
    } catch (err) {
        console.error('Player sync error:', err);
        res.status(500).json({ error: 'Server error' });
    }
});

// POST /api/sync/creators - Import creator content as pending posts (admin only)
router.post('/creators', authenticate, requireAdmin, async (req, res) => {
    try {
        const { posts } = req.body;

        if (!posts || !Array.isArray(posts) || posts.length === 0) {
            return res.status(400).json({ error: 'Posts array required' });
        }

        // Add each post to database
        for (const postData of posts) {
            await db.savePost({
                ...postData,
                status: 'pending'
            });
        }

        // Add notification
        await db.saveNotification({
            type: 'system',
            message: `Content Discovery: ${posts.length} items`,
            details: `Auto-generated posts from trending creators added to quarantine`,
            timestamp: new Date().toLocaleTimeString()
        });

        res.json({
            success: true,
            count: posts.length
        });
    } catch (err) {
        console.error('Creator sync error:', err);
        res.status(500).json({ error: 'Server error' });
    }
});

// GET /api/sync/status - Get sync status
router.get('/status', authenticate, requireAdmin, async (req, res) => {
    try {
        const players = await db.getPlayers();
        const posts = await db.getPosts();
        const pendingPosts = posts.filter(p => p.status === 'pending');
        const autoPosts = posts.filter(p => p.title?.includes('Trending')); // Approximate check for auto posts

        res.json({
            players: {
                count: players.length,
                lastSync: players.length > 0 ? 'Synchronized' : 'No data'
            },
            content: {
                total: posts.length,
                pending: pendingPosts.length,
                autoGenerated: autoPosts.length
            }
        });
    } catch (err) {
        console.error('Sync status error:', err);
        res.status(500).json({ error: 'Server error' });
    }
});

// POST /api/sync/tactics - Sync division tactics (admin only)
router.post('/tactics', authenticate, requireAdmin, async (req, res) => {
    try {
        const { tactics } = req.body;

        if (!tactics || !Array.isArray(tactics) || tactics.length === 0) {
            return res.status(400).json({ error: 'Tactics array required' });
        }

        const result = await db.saveTactics(tactics);

        await db.saveNotification({
            type: 'system',
            message: `Tactical Playbook Synced: ${tactics.length} tactics`,
            details: `Division meta tactics updated from web research`,
            timestamp: new Date().toLocaleTimeString()
        });

        res.json({
            success: true,
            count: result.count
        });
    } catch (err) {
        console.error('Tactics sync error:', err);
        res.status(500).json({ error: 'Server error' });
    }
});

export default router;
