import mongoose from 'mongoose';

const postSchema = new mongoose.Schema({
    title: { type: String, required: true },
    content: { type: String, required: true },
    author: { type: String, required: true },
    category: { type: String, required: true },
    date: { type: String, default: () => new Date().toLocaleDateString() },
    image: { type: String },
    videoUrl: { type: String },
    likedBy: [{ type: mongoose.Schema.Types.ObjectId, ref: 'User' }],
    likes: { type: Number, default: 0 },
    comments: { type: Number, default: 0 },
    viewCount: { type: Number, default: 0 },
    status: { type: String, enum: ['pending', 'approved'], default: 'pending' },
    isAutoGenerated: { type: Boolean, default: false },
    isAiModerated: { type: Boolean, default: true }
}, { timestamps: true });

export const Post = mongoose.model('Post', postSchema);
